title: Elias MÃ¤hler
description: Cybersecurity | Linux | Windows | CTFs
theme: minima

markdown: kramdown
plugins:
  - jekyll-feed

header_pages:
  - about.md
  - projects.md
  - writeups.md
  - contact.md
